site_name: Arkeo Nomad Plugin

theme:
  name: material
  logo: assets/images/horizcicci-trans.png
  favicon: assets/images/CicciFavicon.png
  features:
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.annotate
    - content.code.copy

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - pymdownx.highlight:
      anchor_linenums: false
      linenums: false
      guess_lang: false
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

nav:
  - Introduction: index.md
  - NOMAD Structure: nomad-structure.md

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js
  - js/katex-init.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css
  - assets/stylesheets/extra.css